#!/bin/bash
# Install an optional third-party GumCP module from its upstream project.
#
# These are NOT bundled with GumCP: shipping a copy means shipping whatever
# vulnerabilities that copy had on the day it was vendored, and it silently goes
# stale. Installing from upstream lets you pick — and later update — the version.
#
#   ./scripts/install-module.sh adminer            # default pinned version
#   ./scripts/install-module.sh adminer 4.8.1      # explicit version
#   ./scripts/install-module.sh tinyfilemanager 2.6
#   ./scripts/install-module.sh --list
#
# The upstream file is placed in modules/<name>/vendor/ (blocked from direct web
# access) and reached through a generated entry file that enforces GumCP's login
# before any third-party code runs.

if [ -z "${BASH_VERSION:-}" ]; then exec bash "$0" "$@"; fi
set -u

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

GUMCP_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Defaults are pinned to a known-good release; override with the version argument.
ADMINER_DEFAULT="5.5.1"
TFM_DEFAULT="2.6"

usage() {
    cat <<USAGE
Usage: $(basename "$0") <module> [version]

Modules:
  adminer           Database manager      (upstream: vrana/adminer, default $ADMINER_DEFAULT)
  tinyfilemanager   Web file manager      (upstream: prasathmani/tinyfilemanager, default $TFM_DEFAULT)

Pick versions from the upstream releases pages:
  https://github.com/vrana/adminer/releases
  https://github.com/prasathmani/tinyfilemanager/releases

After installing, enable the module in include/config.php:
  \$gumcp_modules['adminer']['module_active'] = 1;
USAGE
}

[ $# -lt 1 ] && { usage; exit 1; }
case "$1" in -h|--help|--list) usage; exit 0;; esac

MODULE="$1"
VERSION="${2:-}"

case "$MODULE" in
    adminer)
        VERSION="${VERSION:-$ADMINER_DEFAULT}"
        URL="https://github.com/vrana/adminer/releases/download/v${VERSION}/adminer-${VERSION}.php"
        VENDOR_FILE="adminer-${VERSION}.php"
        ENTRY="adminer.php"
        ;;
    tinyfilemanager)
        VERSION="${VERSION:-$TFM_DEFAULT}"
        URL="https://raw.githubusercontent.com/prasathmani/tinyfilemanager/${VERSION}/tinyfilemanager.php"
        VENDOR_FILE="tinyfilemanager-${VERSION}.php"
        ENTRY="tinyfilemanager.php"
        ;;
    *)
        fail "Unknown module '$MODULE'. Run with --list to see the options."
        ;;
esac

DEST="$GUMCP_DIR/modules/$MODULE"
info "Installing $MODULE $VERSION"
info "Source: $URL"

command -v curl >/dev/null 2>&1 || fail "curl is required (sudo apt-get install -y curl)"

mkdir -p "$DEST/vendor" || fail "Could not create $DEST/vendor"

TMP="$(mktemp)"
# -f makes curl fail on 404 so a bad version number is reported, not saved.
if ! curl -fsSL "$URL" -o "$TMP"; then
    rm -f "$TMP"
    fail "Download failed. Does version '$VERSION' exist? See the releases page (--list)."
fi

# Guard against a redirect/error page being saved as if it were the module.
head -c 5 "$TMP" | grep -q '<?php' || { rm -f "$TMP"; fail "Downloaded file is not PHP — aborting."; }

mv "$TMP" "$DEST/vendor/$VENDOR_FILE" || fail "Could not write $DEST/vendor/$VENDOR_FILE"
chmod 644 "$DEST/vendor/$VENDOR_FILE"

# Block direct web access to the raw upstream file: it must only ever be reached
# through the guarded entry file below.
cat > "$DEST/vendor/.htaccess" <<'HT'
# The upstream module file is included by the guarded entry point in the parent
# directory. It must never be served directly — that would bypass the login.
Require all denied
HT

# Generated entry point: enforces GumCP's login before the third-party code runs.
cat > "$DEST/$ENTRY" <<ENTRYPHP
<?php
// Generated by scripts/install-module.sh — do not edit.
// Enforces GumCP authentication before loading the third-party module.
declare(strict_types=1);

define('GUMCP_MODULE_KEY', '$MODULE');
require_once __DIR__ . '/../../include/module_guard.php';

require __DIR__ . '/vendor/$VENDOR_FILE';
ENTRYPHP
chmod 644 "$DEST/$ENTRY"

# Match the web-server ownership the installer sets, when we can.
if id -u www-data >/dev/null 2>&1 && [ "$(id -u)" -eq 0 ]; then
    chown -R www-data:www-data "$DEST"
fi

info "Installed to $DEST"
echo ""
echo "Next: enable it in include/config.php"
echo "    \$gumcp_modules['$MODULE']['module_active'] = 1;"
echo ""
warn "$MODULE is third-party software with its own security history."
warn "Re-run this script with a newer version to update it, and only enable"
warn "modules you actually use."
